const oGamesData = [
		{name:"模拟快餐<br>Fast Food Simulator", counts:0, xxxx:"ffsi"},
		{name:"使命召唤<br>Call of Duty", counts:0, xxxx:"codo"},
		{name:"APEX英雄<br>Apex Legends", counts:0, xxxx:"apex"},
		{name:"城堡王国<br>Kingdoms and Castles", counts:0, xxxx:"kdcs"},
		{name:"史莱姆１<br>Slime Rancher", counts:0, xxxx:"slr1"},
		{name:"中世纪国<br>Medieval Dynasty", counts:0, xxxx:"medd"},
		{name:"传说酒馆<br>Ale & Tale Tavern", counts:0, xxxx:"attv"},
		{name:"国家崛起<br>Rise of Nations", counts:0, xxxx:"rons"},
		{name:"坦克世界<br>World of Tanks", counts:0, xxxx:"wotk"},
		{name:"堡垒之夜<br>Fortnite", counts:0, xxxx:"fort"},
		{name:"小羊肖恩<br>Home Sheep Home", counts:0, xxxx:"home"},
		{name:"幸福工厂<br>Satisfactory", counts:0, xxxx:"sati"},
		{name:"异星探险<br>ASTRONEER", counts:0, xxxx:"astr"},
		{name:"我的世界<br>Minecraft", counts:0, xxxx:"mine"},
		{name:"战争雷霆<br>War Thunder", counts:0, xxxx:"wart"},
		{name:"战舰世界<br>World of Warships", counts:0, xxxx:"wows"},
		{name:"无人深空<br>No Man's Sky", counts:0, xxxx:"nmsk"},
		{name:"潜行者γ<br>S.T.A.L.K.E.R. GAMMA", counts:0, xxxx:"gamm"},
		{name:"灰区战争<br>GRAY ZONE WARFARE", counts:0, xxxx:"gray"},
		{name:"王国重生<br>Kingdoms Rebron", counts:0, xxxx:"king"},
		{name:"纪元1800<br>ANNO 1800", counts:0, xxxx:"an18"},
		{name:"绝地求生<br>PUBG:BATTLEGROUND", counts:0, xxxx:"pubg"},
		{name:"落日余晖<br>Farlight 84", counts:0, xxxx:"fl84"},
		{name:"虚实之间<br>SYNTHETIK", counts:0, xxxx:"synt"},
		{name:"饥荒联机<br>Don't Starve Together", counts:0, xxxx:"dtst"},
		{name:"ＧＴＡ５<br>Grand Theft Auto V", counts:0, xxxx:"gtav"}
];